color0 #1a1a1a
color1 #ff5555
color2 #a6e3a1
color3 #f9e2af
color4 #7a7a7a
color5 #f5c2e7
color6 #94e2d5
color7 #cccccc
color8 #333333
color9 #ff7777
color10 #b9f0b5
color11 #fbe9c3
color12 #a8a8a8
color13 #f7d2ef
color14 #b0f0e5
color15 #ffffff
background #141414
selection_foreground #141414
cursor #ffffff
cursor_text_color #141414
foreground #ffffff
selection_background #a8a8a8
active_border_color #a8a8a8
inactive_border_color #909090

active_tab_foreground   #141414
active_tab_background   #a8a8a8
inactive_tab_foreground #cccccc
inactive_tab_background #232323
cursor_trail_color      #cccccc
