-- Generated by nwg-displays on 2026-09-01 at 15:03:45. Do not edit manually.

hl.monitor({
    output = "desc:Microstep MSI MAG 275QF CE2M225403468",
    mode = "2560x1440@180.0",
    position = "0x0",
    scale = 1,
    vrr = 2
})
hl.monitor({
    output = "desc:Samsung Electric Company LS24AG32x H9JW300342",
    mode = "1920x1080@144.0",
    position = "2560x0",
    scale = 1.0,
    vrr = 0
})
